apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rke2-patcher
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes", "namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: ["helm.cattle.io"]
    resources: ["helmcharts", "helmchartconfigs"]
    verbs: ["get", "list", "watch"]
