apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: rke2-patcher
spec:
  selector:
    matchLabels:
      app: rke2-patcher
  template:
    metadata:
      labels:
        app: rke2-patcher
    spec:
      serviceAccountName: rke2-patcher
      containers:
        - name: rke2-patcher
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: manifests
              mountPath: /var/lib/rancher/rke2/server/manifests
          env:
            - name: MANIFEST_CONTENT
              value: "{{ .Values.manifestContent | default "apiVersion: v1\nkind: ConfigMap\nmetadata:\n  name: example-manifest\ndata:\n  key: value" }}"
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "$MANIFEST_CONTENT" > /var/lib/rancher/rke2/server/manifests/rke2-patcher-manifest.yaml
              exec /rke2-patcher
          securityContext:
            privileged: true
      volumes:
        - name: manifests
          hostPath:
            path: /var/lib/rancher/rke2/server/manifests
            type: Directory
